// Builds src/data/land-mask.generated.ts, the land test behind answer cells, from the 시도 boundaries of
// vuski/admdongkor (https://github.com/vuski/admdongkor), which are derived from Statistics
// Korea SGIS boundaries (KOGL Type 1) and distributed under CC BY 4.0. Download a sido parquet,
// e.g. parquet/sido_20260701.parquet, and pass its path.
//
// A 500 m square counts as land when it touches the boundary polygons at all (its centre lies
// inside one, or a boundary edge passes through it) or lies within about 300 m of a boundary.
// Generous on purpose, so coastal squares, narrow headlands and small islands are never lost.
//
// Usage: pnpm data:land-mask <sido.parquet>
import { writeFile } from "node:fs/promises";
import path from "node:path";
import { asyncBufferFromFile, parquetReadObjects } from "hyparquet";
import proj4 from "proj4";
import { BLOCK_SIZE, SQUARE_SIZE } from "../src/domain/constants";
import { encodeLandMask, LAND, MIXED, SEA, type LandZone } from "../src/domain/land-mask";
import { gridBase, toTM, type Origin, type Point } from "../src/domain/projection";

// A TypeScript module rather than a binary file, so Node scripts and e2e fixtures that compute
// answers can import it as well as the Vite build.
const OUTPUT = new URL("../src/data/land-mask.generated.ts", import.meta.url);
// The source's CRS: EPSG:5179, KGD2002 / Unified CS.
const UTM_K =
  "+proj=tmerc +lat_0=38 +lon_0=127.5 +k=0.9996 +x_0=1000000 +y_0=2000000 +ellps=GRS80 +units=m +no_defs";
const ZONE_BOUNDARY_LNG = 128;
// Each zone keeps a little land past 128°E so squares straddling the boundary are covered.
const ZONE_MARGIN_DEGREES = 0.05;
// Squares this close to a boundary edge also count as land. The boundaries are generalised
// along the coast, and a coastal road's poles can fall just outside them: missing a real answer
// is worse than accepting a little sea next to the shore.
const COAST_BUFFER = 300;
const COAST_BUFFER_OFFSETS = [-COAST_BUFFER, 0, COAST_BUFFER];
// Edges are walked in steps this short, well under a square, so no square they cross is skipped.
const EDGE_STEP = 25;
const SQUARES_PER_BLOCK = BLOCK_SIZE / SQUARE_SIZE;

type Ring = number[][];
type Polygon = Ring[];
type Geometry =
  | { type: "Polygon"; coordinates: Polygon }
  | { type: "MultiPolygon"; coordinates: Polygon[] };

const source = process.argv[2];
if (!source) throw new Error("Usage: pnpm data:land-mask <sido.parquet>");

const rows = await parquetReadObjects({
  file: await asyncBufferFromFile(source),
  columns: ["geom"],
});
const toLngLat = proj4(UTM_K, "EPSG:4326");
const polygons: Polygon[] = rows.flatMap(({ geom }) => {
  const geometry = geom as Geometry;
  const parts = geometry.type === "Polygon" ? [geometry.coordinates] : geometry.coordinates;
  return parts.map((part) =>
    part.map((ring) => ring.map(([x = 0, y = 0]) => toLngLat.forward([x, y]))),
  );
});
console.log(`${source}: ${polygons.length} polygons`);

const zones = (["middle", "east"] as const).map((origin) => rasterize(polygons, origin));
const encoded = encodeLandMask(zones);
const base64 = Buffer.from(encoded).toString("base64");
await writeFile(
  OUTPUT,
  `// Generated by scripts/build-land-mask.ts from ${path.basename(source)}. Do not edit.
// Boundaries: Statistics Korea SGIS (KOGL Type 1), via vuski/admdongkor (CC BY 4.0).
export const LAND_MASK_BASE64 =
  "${base64}";
`,
);
for (const zone of zones) {
  const land = zone.states.filter((state) => state === LAND).length;
  console.log(
    `${zone.origin}: ${zone.columns}×${zone.rows} blocks, ${land} land, ${zone.squares.size} mixed`,
  );
}
console.log(`Wrote ${encoded.length} bytes (${base64.length} as base64) to ${OUTPUT.pathname}`);

// Land squares of one zone, as block states plus square bits for mixed blocks.
function rasterize(lngLatPolygons: Polygon[], origin: Origin): LandZone {
  const onSide = ([lng = 0]: number[]) =>
    origin === "middle"
      ? lng < ZONE_BOUNDARY_LNG + ZONE_MARGIN_DEGREES
      : lng >= ZONE_BOUNDARY_LNG - ZONE_MARGIN_DEGREES;
  const base = gridBase(origin);
  // Offsets from the zone's grid base, in metres.
  const project = ([lng = 0, lat = 0]: number[]): Point => {
    const tm = toTM({ lng, lat }, origin);
    return { x: tm.x - base.x, y: tm.y - base.y };
  };
  const relevant = lngLatPolygons.filter((polygon) => polygon[0]?.some(onSide));
  const projected = relevant.map((polygon) => polygon.map((ring) => ring.map(project)));

  // Square extent: every vertex on this zone's side, rounded out to whole blocks.
  let minX = Infinity;
  let minY = Infinity;
  let maxX = -Infinity;
  let maxY = -Infinity;
  relevant.forEach((polygon, index) =>
    polygon[0]?.forEach((vertex, at) => {
      if (!onSide(vertex)) return;
      const point = projected[index]?.[0]?.[at];
      if (!point) return;
      minX = Math.min(minX, point.x);
      minY = Math.min(minY, point.y);
      maxX = Math.max(maxX, point.x);
      maxY = Math.max(maxY, point.y);
    }),
  );
  const west = blockIndex(minX);
  const south = blockIndex(minY);
  const columns = blockIndex(maxX) - west + 1;
  const rowsOfBlocks = blockIndex(maxY) - south + 1;
  const width = columns * SQUARES_PER_BLOCK;
  const height = rowsOfBlocks * SQUARES_PER_BLOCK;
  const x0 = west * BLOCK_SIZE;
  const y0 = south * BLOCK_SIZE;
  const land = new Uint8Array(width * height);
  const mark = (column: number, row: number) => {
    if (column >= 0 && row >= 0 && column < width && row < height) land[row * width + column] = 1;
  };

  for (const polygon of projected) {
    // Squares a boundary edge passes through.
    for (const ring of polygon) {
      ring.forEach((from, index) => {
        const to = ring[(index + 1) % ring.length];
        if (!to) return;
        const steps = Math.max(1, Math.ceil(Math.hypot(to.x - from.x, to.y - from.y) / EDGE_STEP));
        for (let step = 0; step <= steps; step++) {
          const x = from.x + ((to.x - from.x) * step) / steps;
          const y = from.y + ((to.y - from.y) * step) / steps;
          for (const dx of COAST_BUFFER_OFFSETS) {
            for (const dy of COAST_BUFFER_OFFSETS) {
              mark(
                Math.floor((x + dx - x0) / SQUARE_SIZE),
                Math.floor((y + dy - y0) / SQUARE_SIZE),
              );
            }
          }
        }
      });
    }

    // Squares whose centre is inside: scanlines through each row of centres, even-odd over the
    // polygon's outer ring and holes.
    const crossings: number[][] = [];
    for (const ring of polygon) {
      ring.forEach((from, index) => {
        const to = ring[(index + 1) % ring.length];
        if (!to || from.y === to.y) return;
        const low = Math.min(from.y, to.y);
        const high = Math.max(from.y, to.y);
        const firstRow = Math.max(0, Math.ceil((low - y0) / SQUARE_SIZE - 0.5));
        const lastRow = Math.min(height - 1, Math.floor((high - y0) / SQUARE_SIZE - 0.5));
        for (let row = firstRow; row <= lastRow; row++) {
          const y = y0 + (row + 0.5) * SQUARE_SIZE;
          // Half-open, so a vertex exactly on the scanline is counted once.
          if (y < low || y >= high) continue;
          const x = from.x + ((to.x - from.x) * (y - from.y)) / (to.y - from.y);
          (crossings[row] ??= []).push(x);
        }
      });
    }
    crossings.forEach((xs, row) => {
      xs.sort((a, b) => a - b);
      for (let index = 0; index + 1 < xs.length; index += 2) {
        const start = Math.ceil(((xs[index] ?? 0) - x0) / SQUARE_SIZE - 0.5);
        const end = Math.floor(((xs[index + 1] ?? 0) - x0) / SQUARE_SIZE - 0.5);
        for (let column = start; column <= end; column++) mark(column, row);
      }
    });
  }

  const states = new Uint8Array(columns * rowsOfBlocks);
  const squares = new Map<number, number>();
  for (let blockRow = 0; blockRow < rowsOfBlocks; blockRow++) {
    for (let blockColumn = 0; blockColumn < columns; blockColumn++) {
      let bits = 0;
      for (let row = 0; row < SQUARES_PER_BLOCK; row++) {
        for (let column = 0; column < SQUARES_PER_BLOCK; column++) {
          const at =
            (blockRow * SQUARES_PER_BLOCK + row) * width + blockColumn * SQUARES_PER_BLOCK + column;
          if (land[at]) bits |= 1 << (row * SQUARES_PER_BLOCK + column);
        }
      }
      const index = blockRow * columns + blockColumn;
      states[index] = bits === 0 ? SEA : bits === 0xffff ? LAND : MIXED;
      if (states[index] === MIXED) squares.set(index, bits);
    }
  }
  return { origin, west, south, columns, rows: rowsOfBlocks, states, squares };
}

function blockIndex(metres: number): number {
  return Math.floor(metres / BLOCK_SIZE);
}
