import { decodeLandMask } from "../domain/land-mask";
import { LAND_MASK_BASE64 } from "./land-mask.generated";

// Land squares generated by scripts/build-land-mask.ts.
export const landMask = decodeLandMask(
  Uint8Array.from(atob(LAND_MASK_BASE64), (char) => char.charCodeAt(0)),
);
