import encoded from "./pole-numbers.bin?inline";
import { decodePoleNumbers } from "../domain/pole-number-codec";

// Puzzle pool generated by scripts/sample-pole-numbers.ts. Vite inlines the binary as a
// base64 data URL, so the pool is available synchronously without an extra request.
export const poleNumbers: readonly string[] = decodePoleNumbers(dataUrlBytes(encoded));

function dataUrlBytes(dataUrl: string): Uint8Array {
  const base64 = dataUrl.slice(dataUrl.indexOf(",") + 1);
  return Uint8Array.from(atob(base64), (char) => char.charCodeAt(0));
}
